# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: miku
report_sizes: true
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - main: ./cmd/miku
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      ## <<Stencil::Block(mikuLdflags)>>
      - -X main.version={{ .Version }}
      ## <</Stencil::Block>>
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      ## <<Stencil::Block(mikuExtraArch)>>

      ## <</Stencil::Block>>
    goos:
      - linux
      - darwin
      - windows
      ## <<Stencil::Block(mikuExtraOS)>>

      ## <</Stencil::Block>>
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  # amd64
  - use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jaredallard/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jaredallard/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPL-3.0
    image_templates:
      - "ghcr.io/jaredallard/{{ .ProjectName }}:{{ .Version }}-amd64"
  # arm64
  - use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jaredallard/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jaredallard/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPL-3.0
    image_templates:
      - "ghcr.io/jaredallard/{{ .ProjectName }}:{{ .Version }}-arm64"
docker_manifests:
  - name_template: "ghcr.io/jaredallard/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/jaredallard/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/jaredallard/{{ .ProjectName }}:{{ .Version }}-amd64"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: git
release:
  prerelease: "auto"
  footer: |-
    **Full Changelog**: https://github.com/jaredallard/miku/compare/{{ .PreviousTag }}...{{ .Tag }}

## <<Stencil::Block(extraReleaseOpts)>>

## <</Stencil::Block>>
