version: "3"

tasks:
  default:
    cmds:
      - task: build
  test:
    cmds:
      - go test -v ./...
  build:
    generates:
      - bin/miku
    sources:
      - "./**/*.go"
      - .tool-versions # Trigger rebuild on Go version changes.
    cmds:
      - go build -trimpath -o ./bin/ -v ./cmd/miku
  dev:
    watch: true
    cmds:
      - pkill miku || true
      - task: build
      - ./bin/miku
